/* 宝可梦对战层：好友房使用 webConnect，排位数据使用 B站 Toy JS SDK。 */
(function () {
  'use strict';
  var DATA = (window.POKEDEX_DATA && window.POKEDEX_DATA.pokemon) || [];
  var MAX = 8;
  var ICE = { iceServers: [{ urls: 'stun:stun.l.google.com:19302' }, { urls: 'stun:global.stun.twilio.com:3478' }] };
  var RANK_KEY = 'pokemon_wordle_rating_v1';
  var RANK_BOARD = 1;
  var DIMS = [['hp', 'HP'], ['atk', '攻击'], ['def', '防御'], ['spa', '特攻'], ['spd', '特防'], ['spe', '速度'], ['total', '合计'], ['types', '属性'], ['gen', '世代'], ['ability', '特性'], ['stage', '进化'], ['mega', 'Mega']];
  var $ = function (id) { return document.getElementById(id); };
  var duel = { active: false, role: null, kind: 'friend', wc: null, rtc: null, dc: null, oppId: null, seed: '', code: '', wins: 3, round: 0, score: [0, 0], target: null, guesses: [], oppHits: {}, oppTries: 0, oppOut: false, status: 'idle', settled: false, rating: 1000, profile: null, timer: null };

  function esc(s) { return String(s == null ? '' : s).replace(/[&<>"']/g, function (c) { return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]; }); }
  function pad4(n) { return String(n).padStart(4, '0'); }
  function toast(msg) { var el = $('toast'); if (!el) return; el.textContent = msg; el.classList.add('show'); clearTimeout(toast._t); toast._t = setTimeout(function () { el.classList.remove('show'); }, 2400); }
  function status(msg, id) { var el = $(id || 'duel-status'); if (el) el.textContent = msg; }
  function parse(raw) { try { return typeof raw === 'string' ? JSON.parse(raw) : raw; } catch (e) { return null; } }
  function send(obj) { var raw = JSON.stringify(obj); if (duel.dc && duel.dc.readyState === 'open') duel.dc.send(raw); else if (duel.wc && duel.oppId) duel.wc.Send(raw, { connectId: duel.oppId }); }
  function hash(str) { var h = 2166136261; for (var i = 0; i < str.length; i++) { h ^= str.charCodeAt(i); h = Math.imul(h, 16777619); } return h >>> 0; }
  function pool() { return DATA; }
  function duelTarget(round) { var list = pool(); return list[hash(duel.seed + ':round:' + round) % list.length]; }
  function sameTypes(a, b) { return a.types.length === b.types.length && a.types.every(function (x) { return b.types.indexOf(x) !== -1; }); }
  function sameAbility(a, b) { var x = a.abilities.concat(a.hiddenAbilities), y = b.abilities.concat(b.hiddenAbilities); return x.some(function (v) { return y.indexOf(v) !== -1; }); }
  function hit(p, t, key) { if (key === 'types') return sameTypes(p, t); if (key === 'ability') return sameAbility(p, t); if (key === 'gen') return p.gen === t.gen; if (key === 'mega') return p.canMega === t.canMega; return p[key] === t[key]; }
  function fieldClass(p, t, key) { if (hit(p, t, key)) return 'cell-correct'; if (key === 'types' && p.types.some(function (x) { return t.types.indexOf(x) !== -1; })) return 'cell-close'; if (key === 'ability') return 'cell-far'; if (['hp', 'atk', 'def', 'spa', 'spd', 'spe'].indexOf(key) >= 0 && Math.abs(p[key] - t[key]) <= 10) return 'cell-close'; if (key === 'total' && Math.abs(p.total - t.total) <= 15) return 'cell-close'; if (key === 'stage' && Math.abs(p.stage - t.stage) <= 1) return 'cell-close'; if (key === 'gen' && Math.abs(p.gen - t.gen) <= 1) return 'cell-close'; return 'cell-far'; }
  function value(p, key) { if (key === 'types') return p.types.map(esc).join('/'); if (key === 'ability') return p.abilities.concat(p.hiddenAbilities).map(esc).join('、'); if (key === 'gen') return '第' + p.gen + '世代'; if (key === 'stage') return p.stage + '段'; if (key === 'mega') return p.canMega ? '可' : '不可'; return p[key]; }
  function renderRow(p) {
    var t = duel.target, tr = document.createElement('tr'); tr.className = 'new-row';
    var first = document.createElement('td'); first.className = 'col-poke'; first.innerHTML = '<div class="poke-cell">' + (p.img ? '<img src="' + esc(p.img) + '" alt="" loading="lazy">' : '') + '<div><div class="p-name">' + esc(p.name) + '</div><div class="p-id">#' + pad4(p.id) + '</div></div></div>'; tr.appendChild(first);
    DIMS.forEach(function (d) { var td = document.createElement('td'); var key = d[0], cls = fieldClass(p, t, key); td.className = cls; var v = value(p, key), arrow = ''; if (['hp', 'atk', 'def', 'spa', 'spd', 'spe', 'total', 'stage', 'gen'].indexOf(key) >= 0 && p[key] !== t[key]) arrow = p[key] < t[key] ? '↑' : '↓'; td.innerHTML = '<span class="cell-body"><span class="cell-value">' + v + '</span>' + (arrow ? '<span class="arrow">' + arrow + '</span>' : '') + '</span>'; tr.appendChild(td); });
    $('guess-tbody').appendChild(tr);
  }
  function setTargetVisual() { var img = $('target-img'), overlay = $('target-overlay'); if (!img || !overlay) return; img.className = 'target-img hidden'; overlay.classList.remove('hidden'); overlay.textContent = '?'; }
  function updateUI() { $('duel-score').textContent = duel.score[0] + ' : ' + duel.score[1]; $('duel-round-label').textContent = '第 ' + duel.round + ' 局'; $('attempt-left').textContent = MAX - duel.guesses.length; $('duel-mode-label').textContent = duel.kind === 'ranked' ? '⚔️ 排位对战' : '👥 好友对战'; var dims = $('duel-opp-hits'); if (dims) dims.innerHTML = DIMS.map(function (d) { return '<span class="opp-dim ' + (duel.oppHits[d[0]] ? 'on' : '') + '">' + d[1] + '</span>'; }).join(''); $('duel-opp-tries').textContent = duel.oppTries ? '对手已猜 ' + duel.oppTries + ' 次' : '对手尚未出手'; if (duel.oppOut) $('duel-opp-tries').textContent += '（次数用尽）'; }
  function enterUI() { duel.active = true; $('duel-modal-overlay').classList.remove('open'); $('duel-panel').classList.remove('hidden'); $('setup-card').classList.add('hidden'); $('game-controls').classList.add('hidden'); $('result-banner').classList.add('hidden'); $('btn-duel').classList.add('hidden'); $('btn-rank').classList.add('hidden'); $('btn-duel-leave').classList.remove('hidden'); $('guess-input').disabled = false; $('target-status').textContent = '对战进行中 · 你猜中的反馈会同步给对手'; setTargetVisual(); updateUI(); }
  function reset() { clearTimeout(duel.timer); var wc = duel.wc, dc = duel.dc, rtc = duel.rtc; duel = { active: false, role: null, kind: 'friend', wc: null, rtc: null, dc: null, oppId: null, seed: '', code: '', wins: 3, round: 0, score: [0, 0], target: null, guesses: [], oppHits: {}, oppTries: 0, oppOut: false, status: 'idle', settled: false, rating: duel.rating || 1000, profile: duel.profile || null, timer: null }; if (wc) { try { wc.Disconnect(); } catch (e) {} } if (dc) { try { dc.close(); } catch (e) {} } if (rtc) { try { rtc.close(); } catch (e) {} } }
  function leaveUI() { reset(); $('duel-panel').classList.add('hidden'); $('btn-duel').classList.remove('hidden'); $('btn-rank').classList.remove('hidden'); $('btn-duel-leave').classList.add('hidden'); $('setup-card').classList.remove('hidden'); $('guess-input').disabled = true; $('guess-tbody').innerHTML = ''; $('empty-hint').classList.remove('hidden'); $('target-status').textContent = '选择世代后，点击「开始竞猜」抽取目标'; }
  function beginRound(n) { duel.round = n; duel.target = duelTarget(n); duel.guesses = []; duel.oppHits = {}; duel.oppTries = 0; duel.oppOut = false; duel.status = 'playing'; $('guess-tbody').innerHTML = ''; $('guess-table').classList.add('hidden'); $('empty-hint').classList.remove('hidden'); $('guess-input').disabled = false; $('guess-input').value = ''; setTargetVisual(); updateUI(); $('guess-input').focus(); }
  function endMatch() { duel.status = 'matchEnd'; $('guess-input').disabled = true; var win = duel.score[0] >= duel.wins; status(win ? '🏆 你赢下了整场对战！' : '本场惜败，继续训练再来一局。'); settleRank(win); toast(win ? '🏆 对战胜利' : '对战结束'); }
  function roundEnd(meWin) { if (duel.status !== 'playing') return; duel.status = 'roundEnd'; if (meWin) duel.score[0]++; else duel.score[1]++; updateUI(); if (duel.score[0] >= duel.wins || duel.score[1] >= duel.wins) { endMatch(); return; } status(meWin ? '本局胜利，准备下一局…' : '本局落败，准备下一局…'); if (duel.role === 'host') { duel.timer = setTimeout(function () { var n = duel.round + 1; send({ t: 'start', r: n }); beginRound(n); }, 1200); } }
  function message(raw) { var m = parse(raw); if (!m) return; if (m.t === 'hello') { duel.seed = m.seed; duel.wins = m.wins; send({ t: 'helloAck' }); enterUI(); status('已连接，等待房主开局…'); return; } if (m.t === 'helloAck') { if (duel.role === 'host') { enterUI(); send({ t: 'start', r: 1 }); beginRound(1); } return; } if (m.t === 'start') { enterUI(); beginRound(m.r); return; } if (m.t === 'gi' && m.r === duel.round) { duel.oppTries = m.tries; (m.hits || []).forEach(function (k) { duel.oppHits[k] = true; }); updateUI(); return; } if (m.t === 'win' && m.r === duel.round) { roundEnd(false); return; } if (m.t === 'out' && m.r === duel.round) { duel.oppOut = true; updateUI(); if (duel.guesses.length >= MAX) roundEnd(false); return; } if (m.t === 'forfeit' || m.t === 'leave') { duel.score[1] = duel.wins; endMatch(); } }
  function submit(p) { if (!duel.active || duel.status !== 'playing' || !p) return; if (duel.guesses.some(function (x) { return x.id === p.id; })) { toast('这只宝可梦已经猜过了'); return; } duel.guesses.push(p); renderRow(p); $('guess-table').classList.remove('hidden'); $('empty-hint').classList.add('hidden'); $('guess-input').value = ''; hideSuggest(); var hits = DIMS.filter(function (d) { return hit(p, duel.target, d[0]); }).map(function (d) { return d[0]; }); send({ t: 'gi', r: duel.round, tries: duel.guesses.length, hits: hits }); updateUI(); if (p.id === duel.target.id) { send({ t: 'win', r: duel.round, tries: duel.guesses.length }); roundEnd(true); } else if (duel.guesses.length >= MAX) { send({ t: 'out', r: duel.round }); if (duel.oppOut) roundEnd(false); else { duel.status = 'waiting'; $('guess-input').disabled = true; status('你已用完本局次数，等待对手结束…'); } } }
  function hideSuggest() { var el = $('suggest-list'); if (el) el.classList.remove('open'); }
  function suggestions(q) { var el = $('suggest-list'); if (!el || !duel.active || duel.status !== 'playing' || !q.trim()) { hideSuggest(); return; } var s = q.trim().toLowerCase(), list = DATA.filter(function (p) { return p.name.toLowerCase().indexOf(s) >= 0 || (p.nameEn || '').toLowerCase().indexOf(s) >= 0; }).slice(0, 12); el.innerHTML = list.map(function (p) { return '<div class="suggest-item" data-id="' + p.id + '">' + (p.img ? '<img src="' + esc(p.img) + '" alt="">' : '') + '<div class="si-name">' + esc(p.name) + ' <span>' + esc(p.nameEn || '') + '</span></div><div class="si-id">#' + pad4(p.id) + ' · 第' + p.gen + '世代</div></div>'; }).join(''); el.querySelectorAll('.suggest-item').forEach(function (item) { item.addEventListener('mousedown', function (e) { e.preventDefault(); var p = DATA[Number(item.dataset.id) - 1]; if (p) submit(p); }); }); el.classList.toggle('open', list.length > 0); }
  function copy(text) { if (navigator.clipboard) navigator.clipboard.writeText(text).then(function () { toast('已复制'); }); else toast('请手动复制'); }
  function code() { var chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789', s = ''; for (var i = 0; i < 6; i++) s += chars[Math.floor(Math.random() * chars.length)]; return s; }
  function attachWC() { if (typeof webconnect !== 'function') { status('WebConnect 未加载，请检查网络或使用手动连接。', duel.kind === 'ranked' ? 'rank-status' : 'q-status'); return false; } try { duel.wc = webconnect({ appName: 'pokemon-wordle', channelName: 'pokemon-wordle-room-' + duel.code, connectPassword: 'pokemon-wordle-v1', iceConfiguration: ICE }); } catch (e) { status('连接组件启动失败，请改用手动连接。', duel.kind === 'ranked' ? 'rank-status' : 'q-status'); return false; } duel.wc.onConnect(function (a) { var id = a && a.connectId; if (id && !duel.oppId && (duel.kind === 'ranked' || duel.role === 'host')) duel.wc.Send(JSON.stringify(duel.kind === 'ranked' ? { t: 'rankHello', seed: duel.seed, rating: duel.rating } : { t: 'hello', seed: duel.seed, wins: duel.wins }), { connectId: id }); }); duel.wc.onReceive(function (raw, a) { if (!a || !a.connectId) return; var m = parse(raw); if (!m) return; if (duel.kind === 'ranked') { if (!duel.oppId && m.t === 'rankHello') { duel.oppId = a.connectId; if (String(m.seed) < String(duel.seed)) { duel.seed = m.seed; duel.role = 'guest'; } else duel.role = 'host'; duel.wc.Send(JSON.stringify({ t: 'rankAck', seed: duel.seed }), { connectId: duel.oppId }); enterUI(); status('已匹配到对手，准备开局…', 'rank-status'); if (duel.role === 'host') { setTimeout(function () { if (duel.status !== 'playing') { send({ t: 'start', r: 1 }); beginRound(1); } }, 700); } return; } if (!duel.oppId && m.t === 'rankAck') { duel.oppId = a.connectId; if (m.seed && String(m.seed) < String(duel.seed)) { duel.seed = m.seed; duel.role = 'guest'; } enterUI(); if (duel.role === 'host') { send({ t: 'start', r: 1 }); beginRound(1); } return; } if (a.connectId === duel.oppId) message(m); return; } if (!duel.oppId) { if ((duel.role === 'guest' && m.t === 'hello') || (duel.role === 'host' && m.t === 'helloAck')) duel.oppId = a.connectId; else return; } if (a.connectId === duel.oppId) message(m); }); duel.wc.onDisconnect(function (a) { if (duel.active && a && a.connectId === duel.oppId) { status('对手已断开连接。'); reset(); } }); return true; }
  function createRoom() { reset(); duel.role = 'host'; duel.kind = 'friend'; duel.wins = Number($('duel-wins').value) || 3; duel.code = code(); duel.seed = 'pokemon-room-' + duel.code; $('q-host-box').classList.remove('hidden'); $('q-room-code').textContent = duel.code; status('房间已创建，等待好友加入…', 'q-host-status'); attachWC(); }
  function joinRoom() { var c = $('q-join-code').value.trim().toUpperCase(); if (!c) { toast('请输入房间码'); return; } reset(); duel.role = 'guest'; duel.kind = 'friend'; duel.code = c; duel.seed = ''; status('正在加入房间 ' + c + '…', 'q-status'); attachWC(); }
  function waitIce(pc) { return new Promise(function (resolve) { if (pc.iceGatheringState === 'complete') return resolve(); var done = function () { if (pc.iceGatheringState === 'complete') { pc.removeEventListener('icegatheringstatechange', done); resolve(); } }; pc.addEventListener('icegatheringstatechange', done); setTimeout(resolve, 2500); }); }
  function b64(s) { return btoa(unescape(encodeURIComponent(s))); } function unb64(s) { return decodeURIComponent(escape(atob(s))); }
  function bindDC() { duel.dc.onopen = function () { if (duel.role === 'host') { duel.dc.send(JSON.stringify({ t: 'hello', seed: duel.seed, wins: duel.wins })); status('P2P 已连接，等待确认…', 'm-host-status'); } else { enterUI(); status('已连接，等待房主开局…'); } }; duel.dc.onmessage = function (e) { message(e.data); }; duel.dc.onclose = function () { if (duel.active) toast('对手已断开连接'); }; }
  async function manualHost() { reset(); duel.role = 'host'; duel.kind = 'friend'; duel.wins = Number($('duel-wins').value) || 3; duel.seed = 'pokemon-manual-' + Date.now(); try { duel.rtc = new RTCPeerConnection(ICE); duel.dc = duel.rtc.createDataChannel('pokemon-wordle'); bindDC(); await duel.rtc.setLocalDescription(await duel.rtc.createOffer()); await waitIce(duel.rtc); $('m-invite').value = b64(JSON.stringify(duel.rtc.localDescription)); status('邀请码已生成，发给好友后等待回应码。', 'm-host-status'); } catch (e) { status('生成失败：' + e.message, 'm-host-status'); } }
  async function manualGuest() { var text = $('m-invite-in').value.trim(); if (!text) { toast('请先粘贴邀请码'); return; } reset(); duel.role = 'guest'; try { duel.rtc = new RTCPeerConnection(ICE); duel.rtc.ondatachannel = function (e) { duel.dc = e.channel; bindDC(); }; await duel.rtc.setRemoteDescription(JSON.parse(unb64(text))); await duel.rtc.setLocalDescription(await duel.rtc.createAnswer()); await waitIce(duel.rtc); $('m-answer').value = b64(JSON.stringify(duel.rtc.localDescription)); status('回应码已生成，请发回房主。'); } catch (e) { status('邀请码无效：' + e.message); } }
  async function manualComplete() { try { await duel.rtc.setRemoteDescription(JSON.parse(unb64($('m-answer-in').value.trim()))); status('回应码已接收，正在连接…', 'm-host-status'); } catch (e) { status('回应码无效：' + e.message, 'm-host-status'); } }
  async function profile() { if (!window.toy) return false; try { duel.profile = await toy.getUserProfile(); var saved = await toy.getCloudStorage([RANK_KEY]); var n = Number(saved[RANK_KEY]); duel.rating = Number.isInteger(n) ? Math.max(0, n) : 1000; $('rank-name').textContent = duel.profile.nickname || '排位玩家'; $('rank-rating').textContent = duel.rating; return true; } catch (e) { toast('排位需要登录并授权用户资料'); return false; } }
  async function leaderboard() { if (!window.toy) { $('rank-list').innerHTML = '<div class="rank-empty">请在哔哩哔哩 Toy 中查看排行榜</div>'; return; } $('rank-list').innerHTML = '<div class="rank-empty">排行榜加载中…</div>'; try { await profile(); var period = $('rank-period').value, list = await toy.getRankList({ board: RANK_BOARD, period: period, limit: 50 }); var mine = await toy.getMyRank({ board: RANK_BOARD, period: period }); $('rank-my-official').textContent = mine.ranked ? '官方榜：第 ' + mine.rank + ' 名 · 历史最高 ' + mine.score : '官方榜：暂未上榜'; $('rank-list').innerHTML = list.length ? list.map(function (x) { return '<div class="rank-item"><b>#' + x.rank + '</b><img src="' + esc(x.avatar || '') + '" alt=""><span>' + esc(x.nickname || '训练家') + '</span><strong>' + x.score + '</strong></div>'; }).join('') : '<div class="rank-empty">还没有榜单记录</div>'; } catch (e) { $('rank-list').innerHTML = '<div class="rank-empty">排行榜加载失败，请稍后重试</div>'; } }
  async function settleRank(win) { if (duel.kind !== 'ranked' || duel.settled || !window.toy) return; duel.settled = true; duel.rating = Math.max(0, duel.rating + (win ? 25 : -25)); $('rank-rating').textContent = duel.rating; try { await toy.setCloudStorage((function () { var x = {}; x[RANK_KEY] = String(duel.rating); return x; })()); await toy.submitScore({ board: RANK_BOARD, score: duel.rating }); } catch (e) { status('本场结果已结算，但排位分同步失败，请检查登录状态。'); } }
  function rankMatch() { profile().then(function (ok) { if (!ok) return; if (typeof webconnect !== 'function') { status('WebConnect 未加载，请稍后重试。', 'rank-status'); return; } reset(); duel.kind = 'ranked'; duel.role = 'host'; duel.wins = 2; duel.seed = 'pokemon-ranked-' + Date.now() + '-' + Math.random().toString(36).slice(2); duel.status = 'connecting'; status('正在匹配在线训练家…', 'rank-status'); var oldCode = duel.code; duel.code = 'ranked'; if (!attachWC()) { duel.code = oldCode; return; } }); }
  function init() {
    $('btn-duel').addEventListener('click', function () { $('duel-modal-overlay').classList.add('open'); }); $('btn-rank').addEventListener('click', function () { $('duel-modal-overlay').classList.add('open'); document.querySelector('[data-tab="ranked"]').click(); leaderboard(); }); $('duel-close').addEventListener('click', function () { $('duel-modal-overlay').classList.remove('open'); }); $('duel-create').addEventListener('click', createRoom); $('duel-join').addEventListener('click', joinRoom); $('q-copy-code').addEventListener('click', function () { copy(duel.code); }); $('rank-match').addEventListener('click', rankMatch); $('rank-period').addEventListener('change', leaderboard); $('m-host-gen').addEventListener('click', manualHost); $('m-guest-gen').addEventListener('click', manualGuest); $('m-host-done').addEventListener('click', manualComplete); $('m-copy-invite').addEventListener('click', function () { copy($('m-invite').value); }); $('m-copy-answer').addEventListener('click', function () { copy($('m-answer').value); }); $('btn-duel-leave').addEventListener('click', function () { if (duel.active) send({ t: 'forfeit' }); leaveUI(); }); document.querySelectorAll('.duel-tab').forEach(function (tab) { tab.addEventListener('click', function () { document.querySelectorAll('.duel-tab').forEach(function (t) { t.classList.toggle('active', t === tab); }); ['quick', 'ranked', 'manual'].forEach(function (x) { $('tab-' + x).classList.toggle('hidden', x !== tab.dataset.tab); }); }); }); $('guess-input').addEventListener('input', function () { suggestions(this.value); }); $('guess-input').addEventListener('keydown', function (e) { if (e.key === 'Enter' && duel.active && duel.status === 'playing') { var q = this.value.trim().toLowerCase(), p = DATA.find(function (x) { return x.name.toLowerCase() === q || (x.nameEn || '').toLowerCase() === q; }); if (p) submit(p); else toast('请从联想列表中选择宝可梦'); } }); $('duel-submit-proxy').addEventListener('click', function () { var q = $('guess-input').value.trim().toLowerCase(), p = DATA.find(function (x) { return x.name.toLowerCase() === q || (x.nameEn || '').toLowerCase() === q; }); if (duel.active) { if (p) submit(p); else toast('请先输入完整名称'); } else { $('guess-input').dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true })); } }); }
  window.POKEMON_DUEL = { get active() { return duel.active; }, submit: submit };
  init();
}());
